[tox]
envlist = py39, py310, py311, py312, lint
skipsdist = True

[testenv]
deps =
    -r setup/requirements.txt
    pytest
    gns3fy
    requests
    PyYAML
    pydantic<1.9
setenv =
    PYTHONPATH = {toxinidir}/src
commands =
    pytest tests/

[testenv:lint]
deps = ruff
commands = ruff check src/ tests/
